/**
 * @file    sbit_example_usage.c
 *
 * @brief   Example: Reproduce the reference SBIT exactly.
 *
 * @details This file shows how to populate Sbit_Config_t and call
 *          SBIT_Generate() to produce a byte-identical SBIT every time.
 *
 *          Reference output to match:
 *            Table Type   : 0x5501
 *            Table Length : 0x0126
 *            Num Modules  : 12
 *            Total Regions: 13  (S1=6, S2=4, S3=3)
 *
 * @note    All values that were previously random are now declared here
 *          as constants.  Change them here to get a different but still
 *          deterministic SBIT.
 */

#include "SBIT_GENERATOR.h"

/*==============================================================================
 *              REFERENCE BOOT MESSAGE DIGEST
 *  Pre-computed SHA-256 over the HBL region.
 *  Set all bytes to 0 to have the generator compute it via HSM at runtime.
 *============================================================================*/
static const uint8_t REF_BOOT_DIGEST[SBIT_SHA256_SIZE] =
{
    0x4B, 0x29, 0x80, 0x58, 0xE1, 0xD5, 0xFD, 0x3F,
    0x2F, 0xA2, 0x0E, 0xAD, 0x21, 0x77, 0x39, 0x12,
    0xA5, 0xDC, 0x38, 0xDA, 0x3C, 0x0D, 0xA0, 0xBB,
    0xC7, 0xDE, 0x1A, 0xDF, 0xB6, 0x01, 0x1F, 0x1C
};

/*==============================================================================
 *              REFERENCE SBIT CONFIGURATION
 *
 *  Every field that was previously generated by rand() is now a named
 *  constant below.  To change any value, edit the constant — the
 *  generator will produce the updated SBIT identically on every call.
 *
 *  Module order matches the reference output:
 *    1  HBL_047    0x0047   S1
 *    2  CIB_B      0xFD80   S2
 *    3  MOD_6576   0x6576   S1 + S2
 *    4  MTS_ETM    0xFF00   S2
 *    5  BOOT_UPD   0x0052   S1
 *    6  MOD_0078   0x0078   S1
 *    7  CIB_A      0xFE00   S2
 *    8  MOD_C41A   0xC41A   S1
 *    9  UNUSED     0xFF80   S1
 *   10  MTS_RTM    0xFF80   S3    <- Note: same MID as UNUSED in ref output
 *   11  GEN_DATA   0xFD00   S3
 *   12  MOD_347D   0x347D   S3
 *============================================================================*/

void sbit_BuildReferenceConfig(Sbit_Config_t *cfg)
{
    /* Clear everything first */
    memset(cfg, 0, sizeof(Sbit_Config_t));

    /*------------------------------------------------------------------*/
    /* Header fields                                                     */
    /*------------------------------------------------------------------*/
    cfg->tableType           = SBIT_TABLE_TYPE_V1;
    cfg->unusedUpdateFlag    = 0x01U;
    cfg->mtsUpdateFlag       = 0x01U;
    cfg->cibUpdateFlag       = 0x01U;
    cfg->bootUpdateFlag      = 0x01U;
    cfg->r1AutoVerif         = SBIT_R1_AUTO_VERIF_ENABLED;
    cfg->stage2FailAction    = (uint8_t)SBIT_ACTION_LOCK_IVN_MAC_GEN_AND_VER; /* 0x02 */
    cfg->stage3FailAction    = (uint8_t)SBIT_ACTION_NONE;                     /* 0x00 */
    cfg->fillByte            = 0xA5U;
    cfg->hostReqResetTimeout = 0x0000U;
    cfg->macSbitAddr         = 0x0047FFC0UL;
    cfg->macR1Addr           = SBIT_R1_MAC_ADDR_DEFAULT;   /* 0xFFFFFFFF */

    /* V1: MGAL not used */
    cfg->mgalModuleId        = 0U;

    /* Pre-computed boot digest — generator will use this directly */
    memcpy(cfg->bootMsgDigest, REF_BOOT_DIGEST, SBIT_SHA256_SIZE);

    cfg->numModules          = 12U;

    /* No fault injection */
    cfg->injectFlag          = SBIT_INJECT_NONE;
    cfg->injectValue         = 0U;

    /*------------------------------------------------------------------*/
    /* Module 1: HBL_047  (0x0047)   Stage 1                           */
    /*------------------------------------------------------------------*/
    cfg->modules[0].moduleId   = MOD_ID_HBL_047;
    cfg->modules[0].ccid       = 0xFFFFU;
    cfg->modules[0].numRegions = 1U;
    cfg->modules[0].regions[0].startAddr = SBIT_ADDR_HBL;     /* 0x25C02000 */
    cfg->modules[0].regions[0].length    = SBIT_LEN_HBL;      /* 0x00000380 */
    cfg->modules[0].regions[0].vdIndex   = 1U;
    cfg->modules[0].regions[0].stage     = 1U;

    /*------------------------------------------------------------------*/
    /* Module 2: CIB_B  (0xFD80)   Stage 2                             */
    /*------------------------------------------------------------------*/
    cfg->modules[1].moduleId   = MOD_ID_CIB_B;
    cfg->modules[1].ccid       = 0xC111U;
    cfg->modules[1].numRegions = 1U;
    cfg->modules[1].regions[0].startAddr = 0x25FFEE00UL;
    cfg->modules[1].regions[0].length    = 0x00000900UL;
    cfg->modules[1].regions[0].vdIndex   = 47U;
    cfg->modules[1].regions[0].stage     = 2U;

    /*------------------------------------------------------------------*/
    /* Module 3: MOD_6576  (0x6576)   2 regions: S1 + S2               */
    /*------------------------------------------------------------------*/
    cfg->modules[2].moduleId   = MOD_ID_6576;
    cfg->modules[2].ccid       = 0xBF01U;
    cfg->modules[2].numRegions = 2U;

    cfg->modules[2].regions[0].startAddr = 0x25C05178UL;
    cfg->modules[2].regions[0].length    = 0x00009C08UL;
    cfg->modules[2].regions[0].vdIndex   = 45U;
    cfg->modules[2].regions[0].stage     = 1U;

    cfg->modules[2].regions[1].startAddr = 0x25C0ED80UL;
    cfg->modules[2].regions[1].length    = 0x00001148UL;
    cfg->modules[2].regions[1].vdIndex   = 43U;
    cfg->modules[2].regions[1].stage     = 2U;

    /*------------------------------------------------------------------*/
    /* Module 4: MTS_ETM  (0xFF00)   Stage 2                           */
    /*------------------------------------------------------------------*/
    cfg->modules[3].moduleId   = MOD_ID_ETM;
    cfg->modules[3].ccid       = 0x87E5U;
    cfg->modules[3].numRegions = 1U;
    cfg->modules[3].regions[0].startAddr = 0x25C0FEC8UL;
    cfg->modules[3].regions[0].length    = 0x00004440UL;
    cfg->modules[3].regions[0].vdIndex   = 21U;
    cfg->modules[3].regions[0].stage     = 2U;

    /*------------------------------------------------------------------*/
    /* Module 5: BOOT_UPDATER  (0x0052)   Stage 1                       */
    /*------------------------------------------------------------------*/
    cfg->modules[4].moduleId   = MOD_ID_BOOT_UPDATER;
    cfg->modules[4].ccid       = 0xEB54U;
    cfg->modules[4].numRegions = 1U;
    cfg->modules[4].regions[0].startAddr = 0x25C1A308UL;
    cfg->modules[4].regions[0].length    = 0x00001700UL;
    cfg->modules[4].regions[0].vdIndex   = 5U;
    cfg->modules[4].regions[0].stage     = 1U;

    /*------------------------------------------------------------------*/
    /* Module 6: MOD_0078  (0x0078)   Stage 1                          */
    /*------------------------------------------------------------------*/
    cfg->modules[5].moduleId   = MOD_ID_0078;
    cfg->modules[5].ccid       = 0xD2BEU;
    cfg->modules[5].numRegions = 1U;
    cfg->modules[5].regions[0].startAddr = 0x25C1BA08UL;
    cfg->modules[5].regions[0].length    = 0x000001D0UL;
    cfg->modules[5].regions[0].vdIndex   = 88U;
    cfg->modules[5].regions[0].stage     = 1U;

    /*------------------------------------------------------------------*/
    /* Module 7: CIB_A  (0xFE00)   Stage 2                             */
    /*------------------------------------------------------------------*/
    cfg->modules[6].moduleId   = MOD_ID_CIB_A;
    cfg->modules[6].ccid       = 0x1DE2U;
    cfg->modules[6].numRegions = 1U;
    cfg->modules[6].regions[0].startAddr = SBIT_ADDR_CIB_A;   /* 0x25EFF700 */
    cfg->modules[6].regions[0].length    = 0x00000900UL;
    cfg->modules[6].regions[0].vdIndex   = 46U;
    cfg->modules[6].regions[0].stage     = 2U;

    /*------------------------------------------------------------------*/
    /* Module 8: MOD_C41A  (0xC41A)   Stage 1                          */
    /*------------------------------------------------------------------*/
    cfg->modules[7].moduleId   = MOD_ID_C41A;
    cfg->modules[7].ccid       = 0x4132U;
    cfg->modules[7].numRegions = 1U;
    cfg->modules[7].regions[0].startAddr = SBIT_ADDR_MOD_C41A; /* 0x25C05000 */
    cfg->modules[7].regions[0].length    = SBIT_LEN_MOD_C41A;  /* 0x00000178 */
    cfg->modules[7].regions[0].vdIndex   = 16U;
    cfg->modules[7].regions[0].stage     = 1U;

    /*------------------------------------------------------------------*/
    /* Module 9: UNUSED_FLASH  (0xFF80)   Stage 1                      */
    /*------------------------------------------------------------------*/
    cfg->modules[8].moduleId   = MOD_ID_UNUSED_FLASH;
    cfg->modules[8].ccid       = 0x3C3EU;
    cfg->modules[8].numRegions = 1U;
    cfg->modules[8].regions[0].startAddr = 0x25C1BBD8UL;
    cfg->modules[8].regions[0].length    = 0x00000067UL;
    cfg->modules[8].regions[0].vdIndex   = 58U;
    cfg->modules[8].regions[0].stage     = 1U;

    /*------------------------------------------------------------------*/
    /* Module 10: MTS_RTM  (0xFF80)   Stage 3                          */
    /* Note: MID 0xFF80 appears twice in reference — allowed by spec    */
    /*------------------------------------------------------------------*/
    cfg->modules[9].moduleId   = MOD_ID_MTS_RTM;
    cfg->modules[9].ccid       = 0x4ED2U;
    cfg->modules[9].numRegions = 1U;
    cfg->modules[9].regions[0].startAddr = 0x25C1BC3FUL;
    cfg->modules[9].regions[0].length    = 0x00000093UL;
    cfg->modules[9].regions[0].vdIndex   = 60U;
    cfg->modules[9].regions[0].stage     = 3U;

    /*------------------------------------------------------------------*/
    /* Module 11: GEN_DATA  (0xFD00)   Stage 3                         */
    /*------------------------------------------------------------------*/
    cfg->modules[10].moduleId   = MOD_ID_GEN_DATA;
    cfg->modules[10].ccid       = 0x22F6U;
    cfg->modules[10].numRegions = 1U;
    cfg->modules[10].regions[0].startAddr = 0x25C1BCD2UL;
    cfg->modules[10].regions[0].length    = 0x0000003EUL;
    cfg->modules[10].regions[0].vdIndex   = 17U;
    cfg->modules[10].regions[0].stage     = 3U;

    /*------------------------------------------------------------------*/
    /* Module 12: MOD_347D  (0x347D)   Stage 3                         */
    /*------------------------------------------------------------------*/
    cfg->modules[11].moduleId   = MOD_ID_347D;
    cfg->modules[11].ccid       = 0x4CEDU;
    cfg->modules[11].numRegions = 1U;
    cfg->modules[11].regions[0].startAddr = 0x25C1BD10UL;
    cfg->modules[11].regions[0].length    = 0x00000035UL;
    cfg->modules[11].regions[0].vdIndex   = 52U;
    cfg->modules[11].regions[0].stage     = 3U;
}

/*==============================================================================
 *              ENTRY POINT EXAMPLE
 *============================================================================*/
void sbit_GenerateReference(void)
{
    Sbit_Config_t cfg;
    Sbit_Status_t status;

    sbit_BuildReferenceConfig(&cfg);

    status = SBIT_Generate(&cfg);

    if (status != SBIT_OK)
    {
        /* Handle error — status code identifies the problem */
        (void)status;
    }
}

/*==============================================================================
 *              FAULT INJECTION EXAMPLE
 *  Shows how to produce a corrupted SBIT for negative testing.
 *  Only injectFlag and injectValue change — everything else is identical.
 *============================================================================*/
void sbit_GenerateWithInvalidTableLength(void)
{
    Sbit_Config_t cfg;

    sbit_BuildReferenceConfig(&cfg);

    cfg.injectFlag  = SBIT_INJECT_TABLE_LENGTH;
    cfg.injectValue = 0x0010U;   /* Too small — HSM should reject */

    (void)SBIT_Generate(&cfg);
}

void sbit_GenerateWithR1InStage2(void)
{
    Sbit_Config_t cfg;

    sbit_BuildReferenceConfig(&cfg);

    /* Move VD=1 (R1) to appear as a Stage 2 region */
    cfg.modules[0].regions[0].stage = 2U;   /* HBL region moved to S2 */
    cfg.injectFlag  = SBIT_INJECT_R1_IN_STAGE2;
    cfg.injectValue = 0U;

    (void)SBIT_Generate(&cfg);
}

void sbit_GenerateWithInvalidVdS1(void)
{
    Sbit_Config_t cfg;

    sbit_BuildReferenceConfig(&cfg);

    cfg.injectFlag  = SBIT_INJECT_INVALID_VD_S1;
    cfg.injectValue = 0x00U;   /* VD index 0 is invalid */

    (void)SBIT_Generate(&cfg);
}
